name: Frontend CD - QA

on:
  workflow_run:
    workflows: ["Frontend CI - QA"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.34.1

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Update frontend image (QA)
        run: |
          kubectl set image deployment/frontend-deployment frontend=karanam08/frontend:qa -n qa

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/frontend-deployment -n qa
